### ISSUE TITLE
Support for more than 8-bit input images

### ISSUE THREAD

**Issue by IS4Code** [pornel/undither#3]
I know 8-bit indexed images are the usual candidates for this process, but is limiting the palette size really necessary? I have images with 512 colors and I would like to try this on them. If you could, please allow any type of PNG image as the input, and create the palette from its individual colors, if more than 256 colors can be taken by the algorithm.

**Comment by kornelski** [comment]
The whole point of this algorithm is to read thresholds from the palette. It automatically adapts to images, because it tries to reverse-engineer how the image was made and guess which pixels are from dithering and which are edges.

Just any image that happens to have 512 colors wouldn't work, unless you've created that image from a tool that uses 512-entry palette with dithering. There aren't many such tools, which is why I don't support it.
